apiVersion: apps/v1
kind: Deployment
metadata:
  name: chathura-eureka-dev
  labels:
    app: chathura-eureka-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chathura-eureka-dev
  template:
    metadata:
      labels:
        app: chathura-eureka-dev
    spec:
      imagePullSecrets:
        - name: gar-secret      
      containers:
      - name: chathura-eureka-dev
        image: DIT # Image tag will be replaced by shared library
---
apiVersion: v1
kind: Service
metadata:
  name: chathura-eureka-dev
  labels:
    app: chathura-eureka-dev
spec:
  #type: NodePort
  ports:
  - port: 8761
    targetPort: 8761
  #  NodePort: 31512 2333
  selector:
    app: chathura-eureka-dev

 #   edit docker file
 # added image ss