apiVersion: apps/v1
kind: Deployment
metadata:
  name: chathura-eureka-dev
  labels:
    app: chathura-eureka-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chathura-eureka-dev
  template:
    metadata:
      labels:
        app: chathura-eureka-dev
  spec:
    - name:
      containers:
      image: DIT # Image tag will be replaced by shared library
---
apiVersion: v1 
kind: Service
metadata:
  name: chathura-eureka-dev
  labels:
    app: chathura-eureka-dev
spec:
  ports:
   - port: 80
     targetPort: 8761
  selector:
    app: chathura-eureka-dev       
      